extends Node
## Tiny translation table (Dutch + English). Picks Dutch for nl/be locales.

var lang := "en"

const TEXT := {
	"title": ["ZOMBIE DORP", "ZOMBIE VILLAGE"],
	"subtitle": ["Verzamel. Bouw. Overleef.", "Gather. Build. Survive."],
	"play": ["SPELEN", "PLAY"],
	"how": ["HOE SPEEL JE?", "HOW TO PLAY"],
	"sound_on": ["GELUID: AAN", "SOUND: ON"],
	"sound_off": ["GELUID: UIT", "SOUND: OFF"],
	"best": ["Record", "Best"],
	"day": ["DAG", "DAY"],
	"night": ["NACHT", "NIGHT"],
	"night_comes": ["De nacht valt... ze komen eraan!", "Night falls... they are coming!"],
	"day_comes": ["Je hebt de nacht overleefd!", "You survived the night!"],
	"gather_hint": ["Verzamel spullen en bouw barricades!", "Gather supplies and build barricades!"],
	"zombies_left": ["Zombies", "Zombies"],
	"paused": ["PAUZE", "PAUSED"],
	"resume": ["VERDER", "RESUME"],
	"menu": ["MENU", "MENU"],
	"game_over": ["JE BENT OPGEGETEN!", "YOU GOT EATEN!"],
	"survived": ["Nachten overleefd", "Nights survived"],
	"kills": ["Zombies verslagen", "Zombies defeated"],
	"score": ["Score", "Score"],
	"new_best": ["NIEUW RECORD!", "NEW HIGHSCORE!"],
	"again": ["OPNIEUW", "TRY AGAIN"],
	"not_enough": ["Niet genoeg spullen!", "Not enough supplies!"],
	"cant_build": ["Hier kun je niet bouwen", "You can't build here"],
	"no_ammo": ["Geen kogels!", "No ammo!"],
	"searched": ["Al doorzocht", "Already searched"],
	"found": ["Gevonden", "Found"],
	"empty": ["Leeg...", "Empty..."],
	"ate": ["Lekker! +HP", "Yum! +HP"],
	"no_food": ["Geen eten", "No food"],
	"full_hp": ["Je bent al gezond", "Already healthy"],
	"reloaded": ["Toren bijgevuld", "Turret reloaded"],
	"wood": ["Hout", "Wood"],
	"stone": ["Steen", "Stone"],
	"scrap": ["Schroot", "Scrap"],
	"ammo": ["Kogels", "Ammo"],
	"food": ["Eten", "Food"],
	"b_barricade": ["Barricade", "Barricade"],
	"b_wall": ["Stenen muur", "Stone wall"],
	"b_spikes": ["Spijkerval", "Spike trap"],
	"b_turret": ["Geschut", "Turret"],
	"b_campfire": ["Kampvuur", "Campfire"],
	"search": ["E: doorzoeken", "E: search"],
	"refill": ["E: kogels erin", "E: add ammo"],
	"help_title": ["HOE SPEEL JE?", "HOW TO PLAY"],
	"help_text": [
		"OVERDAG: hak bomen (hout), sla rotsen (steen) en doorzoek huizen en kratten (schroot, kogels, eten).\n'S NACHTS: zombies komen over de wegen het dorp in. Bouw barricades en overleef!\n\nWASD / ZQSD / pijltjes: lopen\nLinks klikken / spatie: bijl\nRechts klikken / F: schieten\n1-5: bouwen kiezen, klik om te plaatsen\nE: doorzoeken / winkel / auto   R: eten\nTab / muiswiel: ander geweer   N: nacht starten\n\nVersla zombies voor MUNTEN en koop wapens. Red mensen die HELP! roepen: ze helpen je. Maak de auto en rijd naar een nieuw gebied!",
		"DAY: chop trees (wood), break rocks (stone) and search houses and crates (scrap, ammo, food).\nNIGHT: zombies walk into the village along the roads. Build barricades and survive!\n\nWASD / arrows: move\nLeft click / space: axe\nRight click / F: shoot\n1-5: pick a building, click to place\nE: search / shop / car   R: eat\nTab / mouse wheel: switch gun   N: start night\n\nDefeat zombies for COINS and buy weapons. Rescue people shouting HELP!: they help you. Fix the car and drive to a new area!"
	],
	"back": ["TERUG", "BACK"],
	"build_mode": ["Klik om te bouwen - rechts klikken stopt", "Click to build - right click cancels"],
	"build_mode_touch": ["Tik BOUW om te plaatsen", "Tap BUILD to place"],
	"place": ["BOUW", "BUILD"],
	"credits": ["Muziek & geluid: zie CREDITS", "Music & sound: see CREDITS"],
	"coins": ["Munten", "Coins"],
	"shop": ["E: wapenwinkel", "E: weapon shop"],
	"shop_title": ["WAPENWINKEL", "WEAPON SHOP"],
	"shop_closed": ["De winkel is 's nachts dicht!", "The shop is closed at night!"],
	"buy": ["KOOP", "BUY"],
	"equip": ["PAKKEN", "EQUIP"],
	"equipped": ["IN HAND", "EQUIPPED"],
	"close": ["SLUITEN", "CLOSE"],
	"bought": ["Gekocht!", "Bought!"],
	"no_coins": ["Niet genoeg munten!", "Not enough coins!"],
	"damage": ["schade", "damage"],
	"w_axe": ["Bijl", "Axe"],
	"w_bat": ["Knuppel", "Baseball bat"],
	"w_machete": ["Machete", "Machete"],
	"w_chainsaw": ["Kettingzaag", "Chainsaw"],
	"w_pistol": ["Pistool", "Pistol"],
	"w_shotgun": ["Jachtgeweer", "Shotgun"],
	"w_smg": ["Machinegeweer", "Machine gun"],
	"w_ammo_pack": ["20 kogels", "20 bullets"],
	"w_food_pack": ["2x eten", "2x food"],
	"d_bat": ["Slaat zombies ver weg", "Knocks zombies far away"],
	"d_machete": ["Hard en snel", "Strong and fast"],
	"d_chainsaw": ["Zaagt alles kapot!", "Cuts through everything!"],
	"d_shotgun": ["6 hagels per schot", "6 pellets per shot"],
	"d_smg": ["Supersnel schieten", "Super fast shooting"],
	"d_ammo_pack": ["Voor je geweren", "For your guns"],
	"d_food_pack": ["+30 HP per stuk", "+30 HP each"],
	"van_repair": ["E: auto maken", "E: fix the car"],
	"van_go": ["E: wegrijden naar een nieuw gebied!", "E: drive to a new area!"],
	"van_fixed": ["De auto is gemaakt!", "The car is fixed!"],
	"van_night": ["'s Nachts rijden is te gevaarlijk!", "Too dangerous to drive at night!"],
	"van_need": ["Nodig", "Needed"],
	"travel_to": ["Op weg naar", "Driving to"],
	"area": ["Gebied", "Area"],
	"areas": ["Gebieden bereikt", "Areas reached"],
	"swapped": ["Wapen", "Weapon"],
	"help_me": ["HELP!", "HELP!"],
	"rescue": ["E: meenemen", "E: take along"],
	"joined": ["helpt je nu!", "joins your team!"],
	"downed": ["is gewond! Morgen weer beter.", "is hurt! Better tomorrow."],
	"revived": ["is weer beter!", "is back on their feet!"],
	"role_shooter": ["schutter", "shooter"],
	"role_fighter": ["vechter", "fighter"],
	"role_medic": ["dokter", "medic"],
	"role_builder": ["bouwer", "builder"],
	"chopped": ["heeft hout gehakt", "chopped some wood"],
	"rescued": ["Mensen gered", "People rescued"],
}

func _ready() -> void:
	var loc := OS.get_locale_language()
	lang = "nl" if loc in ["nl", "af"] else "en"

func t(key: String) -> String:
	if not TEXT.has(key):
		return key
	return TEXT[key][0 if lang == "nl" else 1]
